### ISSUE TITLE
[Feature request] Add a `catchError` alias for `PromiseTools.catch_` method

### ISSUE THREAD

**Issue by CedX** [chfoo/thenshim#1]
`catch_` as method name feels a bit weird to me. It looks like the name of a "magic method", and when you are used to code in JavaScript, it's fairly easy to forget the underscore while typing.

The `js.lib.Promise` class uses `catchError` as method name, so to be consistent, I think that `PromiseTools` should also use `catchError` instead of `catch_`.

Renaming the method would be a breaking change, so I propose to add an alias.

**Comment by chfoo** [comment]
Added in version 1.1.0 which I just released as a zip right now

**Comment by CedX** [comment]
Thanks a lot @chfoo !
