### ISSUE TITLE
Check support for PHP target

### ISSUE THREAD

**Issue by CedX** [chfoo/thenshim#2]
See this project: https://github.com/cedx/which.hx
It's a cross platform project: I test it on Eval (`--interp`), JS, Neko and PHP.

With the PHP target, I always get this error:
`ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'php\_Boot\HxString' does not have a method 'then' in /home/runner/work/which.hx/which.hx/lib/php/php/_Boot/HxDynamicStr.php:93`

See the CI: https://github.com/cedx/which.hx/runs/804396168
All tested targets are OK, except PHP.

This error is raised by the call to `Reflect.callMethod()` in [`thenshim/fallback/HandlerSession.resolvePromiseObject()` method](https://github.com/chfoo/thenshim/blob/master/src/thenshim/fallback/HandlerSession.hx#L135):
the received `object` argument is a plain PHP string (i.e. the result of the resolved promise) so there is no `.then()` method attached to it.

I have strictly no idea if it is an error in the `thenshim` package, in the Haxe compiler or my own code (my intuition is: the Haxe compiler).
My request: could you test your package with the PHP target to ensure that your tests are OK on this target?

Haxe: v4.1.2 on Windows x64
`thenshim`: v1.1.0

**Comment by chfoo** [comment]
I think I found the issue which my unit tests didn't cover. PHP strings get wrapped in HxDynamicStr which always returns a wrapper for getting properties, but strings shouldn't be in that Promise/A+ code path anyway. I pushed a fix and if this is correct, I can release a new Haxe lib.

**Comment by CedX** [comment]
I've integrated your commit 0b3901f and now my tests succeed ! 🥰

**Comment by chfoo** [comment]
Thanks for confirming, I released a zip under version 1.1.1 now.

**Comment by CedX** [comment]
Thanks a lot @chfoo !!!
