### ISSUE TITLE
Wrong inferred result type in thennable callback

### ISSUE THREAD

**Issue by alexeychikk** [chfoo/thenshim#3]
I think the type of result in `then` callback might be wrong. When I return `sleep(1000)` promise of type `Promise<Never>` from the first `then` callback, I expect to get unwrapped type as a result in the second `then` callback e.g. `Never` (like in TypeScript), but I get `Promise<Never>`.
Is this a bug or maybe I can somehow hint the compiler to clarify the type?

```haxe
import haxe.Timer;
import thenshim.Promise;

typedef Never = Null<Bool>;

class Main {
	static public function main() {
		var start = Sys.time() * 1000;
		var promise:Promise<Never> = Promise.resolve(null);
		promise.then((res:Never) -> sleep(1000)).then((res:Never) -> {
			//                                     ^^^^^^^^^
			//                                     res is inferred as Promise<Never>
			trace(Sys.time() * 1000 - start);
		});
	}
}

function sleep(ms:Int = 0):Promise<Never> {
	return new Promise<Never>((resolve, reject) -> Timer.delay(() -> resolve(null), ms));
}
```

```console
src/Main.hx:10: lines 10-12 : (res : Never) -> Void should be thenshim.ThenableCallback<thenshim.Promise<Never>, Void>
src/Main.hx:10: lines 10-12 : ... For function argument 'onFulfilled'
```

**Comment by chfoo** [comment]
It's been a long time since I worked on this code, but if I can remember correctly, your second `then()` needs a return value such as returning `null` after your `trace()`. (When I wrote the library, I could only get it to work with `T‑>Promise<R>`, `T‑>Thenable<R>`, `T‑>R`. I don't think `T->void` to match JavaScript was possible in Haxe at that time.)

**Comment by alexeychikk** [comment]
I figured out a way, you can just `cast` a callback:
```haxe
Promise.resolve(null).then((res) -> sleep(1000))
  .then(cast function(res: Never) { 
    trace(Sys.time() * 1000 - start);
  });
```
It's safe because `res` actually has type `Never` and not `Promise<Never>` as inferred without a `cast`.
